coverage:
  precision: 0
  round: down
  range: "80..100"
  status:
    project:
      default:
        target: auto
        threshold: 20 # Project is still small so high variations can still happen.
    patch: off

comment:
  layout: "diff, files, components"

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
  individual_components:
    - component_id: dns_lib
      name: dns_lib
      paths:
        - lib/**
    - component_id: dns_cli
      name: dns_cli
      paths:
        - cli/**
