coverage:
  precision: 0
  round: down
  range: "80..100"
  status:
    project:
      default:
        target: auto
        threshould: 20 # Project is still small so high variations can still happen.
    project:
      default:
        target: auto
        threshould: 20 # Project is still small so high variations can still happen.

comment:
  layout: "diff, files, components"

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
  individual_components:
    - component_id: dns_lib
      name: dns_lib
      paths:
        - lib/src/lib.rs
        - lib/src/*
