[package]
name = "dns_cli"
version = "0.1.0"
description = "A DNS lookup utility"

rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
dns_lib = { path = "../lib" }
